apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: danicuestam-dev
  name: ubuntu-hello
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/DaniCuesta/docker-images.git'
      ref: main
    contextDir: /ubuntu-hello
    sourceSecret:
      name: github-credentials
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: DockerImage
      name: 'quay.io/danicuestam/ubuntu-hello:latest'
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: github-webhook-secret