kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: quay-reposit-java-app-bc-demo
  namespace: danicuestam-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'quay.io/danicuestam/java-app-demo:v2.0'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'java-app-is-demo:latest'
  postCommit: {}
  source:
    type: None
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: 'java-app-is-demo:latest'
        paused: true
    - type: ConfigChange
  runPolicy: Serial