kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-app-deployment-demo
  namespace: danicuestam-dev
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: '19'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"java-app-is-demo:stable"},"fieldPath":"spec.template.spec.containers[?(@.name==\"java-app-container-demo\")].image","paused":
      false}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app-demo
      annotations:
        openshift.openshift.io/restartedAt: '2023-10-30T15:18:53.982Z'
    spec:
      containers:
        - name: java-app-container-demo
          image: >-
            quay.io/danicuestam/java-app-demo@sha256:867f34793bc9647ed01abd40540c84963704c3feddc54b73e7dae5b1bcde6e84
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600