kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: openjdk-11
  namespace: danicuestam-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 1.16-1
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/danicuestam/openjdk-11:1.16-1'
      generation: 4
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source