apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: quay.io/danicuestam/mysql-custom:v1.0 # Ejemplo: mysql:latest
      imagePullSecrets:
        - name: quayio
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: mi_basededatos
            - name: MYSQL_USER
              value: mi_usuario
            - name: MYSQL_PASSWORD
              value: mi_contraseña
